export {
  AxAuthorizationDeniedError,
  axAttenuateAuthority,
  axAuthorityClaim,
  axAuthorize,
  axFunctionAuthorityTarget,
  axSnapshotAuthority,
  axValidateCapabilityGrant,
} from './authority.js';
export {
  axCollectGrantRequirements,
  axEvaluateGuards,
  axIsEvidenceRequirement,
  axIsGuardPredicateFailure,
} from './evidence.js';
export type {
  AxActor,
  AxAuthorityClaim,
  AxAuthorityContext,
  AxAuthorityDelegationOptions,
  AxAuthorityInheritance,
  AxAuthorityValue,
  AxAuthorizationAuditEvent,
  AxAuthorizationReceipt,
  AxAuthorizationRequestContext,
  AxAuthorizer,
  AxCapabilityGrant,
  AxDelegationClaims,
  AxEvidenceMatch,
  AxEvidenceObservation,
  AxEvidenceRequirement,
  AxGuardEvaluation,
  AxGuardEvaluationContext,
  AxGuardFailure,
  AxGuardFailureCode,
  AxGuardOp,
  AxPrincipal,
  AxResourceScope,
} from './types.js';
