export {
  AxAuthorizationDeniedError,
  axAttenuateAuthority,
  axAuthorityClaim,
  axAuthorize,
  axFunctionAuthorityTarget,
  axSnapshotAuthority,
  axValidateCapabilityGrant,
} from './authority.js';
export type {
  AxActor,
  AxAuthorityClaim,
  AxAuthorityContext,
  AxAuthorityDelegationOptions,
  AxAuthorityInheritance,
  AxAuthorityValue,
  AxAuthorizationAuditEvent,
  AxAuthorizationReceipt,
  AxAuthorizationRequestContext,
  AxAuthorizer,
  AxCapabilityGrant,
  AxDelegationClaims,
  AxPrincipal,
  AxResourceScope,
} from './types.js';
