import { readFile } from 'node:fs/promises';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import {
  listSmokeLockfiles,
  lockedAxllmVersion,
  readRustPackageVersion,
  smokeLockfileRepoRoot as repoRoot,
  setLockedAxllmVersion,
  syncSmokeLockfiles,
} from './lib/smoke-lockfiles.mjs';

const sample = [
  '# This file is automatically @generated by Cargo.',
  'version = 4',
  '',
  '[[package]]',
  'name = "axllm"',
  'version = "1.2.3"',
  'dependencies = [',
  ' "regex",',
  ']',
  '',
  '[[package]]',
  'name = "regex"',
  'version = "1.12.4"',
  '',
].join('\n');

describe('smoke lockfile sync', () => {
  it('reads and rewrites only the axllm path-dependency version', () => {
    expect(lockedAxllmVersion(sample)).toBe('1.2.3');
    const next = setLockedAxllmVersion(sample, '24.0.17');
    expect(lockedAxllmVersion(next)).toBe('24.0.17');
    expect(next).toBe(
      sample.replace('version = "1.2.3"', 'version = "24.0.17"')
    );
    expect(next).toContain('version = "1.12.4"');
  });

  it('rejects a lockfile without an axllm entry', () => {
    expect(() => lockedAxllmVersion('[[package]]\nname = "regex"\n')).toThrow(
      /no axllm package entry/
    );
  });

  it('finds every committed Rust smoke lockfile', async () => {
    const locks = await listSmokeLockfiles(repoRoot);
    expect(locks.length).toBeGreaterThan(0);
    for (const lock of locks) {
      expect(path.basename(lock)).toBe('Cargo.lock');
    }
  });

  // Regression guard for the drift that made `npm test` dirty a clean
  // checkout: every committed smoke lockfile must already pin the current
  // packages/rust version, so `cargo build` has nothing to rewrite.
  it('keeps every committed smoke lockfile at the current axllm version', async () => {
    const version = await readRustPackageVersion(repoRoot);
    for (const lock of await listSmokeLockfiles(repoRoot)) {
      expect(lockedAxllmVersion(await readFile(lock, 'utf8'))).toBe(version);
    }
    const { stale } = await syncSmokeLockfiles({ repoRoot, check: true });
    expect(stale).toEqual([]);
  });
});
